# Generated by Django 5.2.6 on 2025-09-17 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50, verbose_name='marca')),
                ('modelo', models.CharField(max_length=50, verbose_name='modelo')),
                ('año', models.DateField(verbose_name='año')),
            ],
        ),
    ]
